apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::880987042267:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::880987042267:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-988JXUGLNIV5
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-06-18T12:06:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "40570"
  uid: ff9531ad-2a8c-41b1-9b11-a2c5a005f874
